export enum NotificationType {
  ORDER_APPROVED_FINAL_PRICE = 'ORDER_APPROVED_FINAL_PRICE',
  NO_DRIVER_AVAILABLE = 'NO_DRIVER_AVAILABLE',
  PAYMENT_TIMEOUT = 'PAYMENT_TIMEOUT',
  ORDER_ASSIGNED = 'ORDER_ASSIGNED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  OTP_ISSUED = 'OTP_ISSUED',
  PAYMENT_RECONCILIATION_REQUIRED = 'PAYMENT_RECONCILIATION_REQUIRED',
}
